name: Deploy to WordPress.org
on:
  push:
    branches:
    - master
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress Plugin Deploy
      uses: varunsridharan/action-wp-org-deploy@master
      with:
        WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        SLUG: post-classified-for-docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}